server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh             #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由

        - id: payment_routh2             #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**      #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示是否讲自己注册进Eureka Server默认为true
    service-url:
      register-with-eureka: true
      fetch-registry: true
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka7001.com:7001/eureka

